# Generated by Django 4.2.7 on 2025-11-19 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.IntegerField(default=1, verbose_name='Текущая неделя')),
                ('total_weeks', models.IntegerField(default=12, verbose_name='Всего недель')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='Начальный капитал')),
                ('current_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='Текущий капитал')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('instrument_type', models.CharField(choices=[('deposit', 'Банковский вклад'), ('stocks', 'Акции'), ('bonds', 'Облигации')], max_length=20, verbose_name='Тип инструмента')),
                ('base_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Базовая доходность (%)')),
                ('risk_level', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], verbose_name='Уровень риска')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('event_type', models.CharField(choices=[('positive', 'Положительное'), ('negative', 'Отрицательное'), ('neutral', 'Нейтральное')], max_length=20, verbose_name='Тип события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('return_modifier', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Модификатор доходности (%)')),
                ('affected_instruments', models.ManyToManyField(to='game.investmentinstrument', verbose_name='Затронутые инструменты')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма инвестиции')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='game.gamesession')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.investmentinstrument', verbose_name='Инструмент')),
            ],
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='Номер недели')),
                ('capital_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Капитал до')),
                ('capital_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Капитал после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.marketevent', verbose_name='Событие')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.gamesession')),
            ],
        ),
    ]
